import Link from "next/link";
import { notFound } from "next/navigation";
import { marked } from "marked";
import { Download } from "lucide-react";

import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  RegenerateOneButton,
} from "@/components/deliverables/deliverable-actions";
import { PrintButton } from "@/components/deliverables/print-button";
import { prisma } from "@/lib/prisma";
import { cn } from "@/lib/utils";
import {
  DELIVERABLE_TYPES,
  DELIVERABLE_TYPE_LABELS,
  type DeliverableType,
} from "@/types";

function isDeliverableType(v: string): v is DeliverableType {
  return (DELIVERABLE_TYPES as readonly string[]).includes(v);
}

// Configure marked once per server invocation. The markdown is generated by
// our own engines so XSS isn't a concern — but we still use `breaks: true`
// to keep line breaks predictable in the rendered output.
marked.setOptions({ breaks: true, gfm: true });

export default async function DeliverablePreviewPage(
  props: PageProps<"/projects/[id]/deliverables/[type]">,
) {
  const { id, type } = await props.params;
  if (!isDeliverableType(type)) notFound();

  const project = await prisma.project.findUnique({
    where: { id },
    select: { id: true, name: true },
  });
  if (!project) notFound();

  const persisted = await prisma.deliverable.findFirst({
    where: { projectId: id, type },
    orderBy: { createdAt: "desc" },
  });

  const label = DELIVERABLE_TYPE_LABELS[type];

  if (!persisted) {
    return (
      <div className="mx-auto max-w-3xl space-y-4">
        <Breadcrumb projectId={project.id} projectName={project.name} typeLabel={label} />
        <div className="rounded-md border border-dashed border-border bg-muted/30 p-6 text-center text-sm">
          <p className="mb-3 text-muted-foreground">
            Ce livrable n&apos;a pas encore été généré.
          </p>
          <RegenerateOneButton projectId={project.id} type={type} label="Générer maintenant" />
        </div>
      </div>
    );
  }

  const html = await marked.parse(persisted.content);

  return (
    <div className="mx-auto max-w-3xl space-y-4">
      <div className="print:hidden">
        <Breadcrumb projectId={project.id} projectName={project.name} typeLabel={label} />
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3 print:hidden">
        <div className="space-y-0.5">
          <h2 className="text-xl font-semibold tracking-tight">{label}</h2>
          <p className="text-xs text-muted-foreground">
            Dernière génération :{" "}
            {persisted.createdAt.toLocaleString("fr-FR", {
              dateStyle: "short",
              timeStyle: "short",
            })}{" "}
            · format {persisted.format}{" "}
            <Badge variant="outline" className="ml-1 text-[10px]">
              {persisted.content.length.toLocaleString("fr-FR")} car.
            </Badge>
          </p>
        </div>
        <div className="flex items-center gap-1.5">
          <a
            href={`/projects/${project.id}/deliverables/${type}/download`}
            className={cn(buttonVariants({ variant: "outline" }))}
            download
          >
            <Download className="mr-2 size-4" />
            Télécharger .md
          </a>
          <PrintButton />
          <RegenerateOneButton projectId={project.id} type={type} label="Régénérer" />
        </div>
      </div>

      <article
        className="deliverable-prose"
        dangerouslySetInnerHTML={{ __html: html }}
      />

      <div className="flex justify-between gap-2 border-t border-border pt-4 print:hidden">
        <Link
          href={`/projects/${project.id}/deliverables`}
          className={buttonVariants({ variant: "outline" })}
        >
          ← Tous les livrables
        </Link>
        <Link
          href={`/projects/${project.id}`}
          className={buttonVariants({ variant: "ghost" })}
        >
          Retour au projet →
        </Link>
      </div>
    </div>
  );
}

function Breadcrumb({
  projectId,
  projectName,
  typeLabel,
}: {
  projectId: string;
  projectName: string;
  typeLabel: string;
}) {
  return (
    <div className="flex items-center gap-2 text-xs text-muted-foreground">
      <Link href="/projects" className="hover:underline">
        Projets
      </Link>
      <span>/</span>
      <Link href={`/projects/${projectId}`} className="hover:underline">
        {projectName}
      </Link>
      <span>/</span>
      <Link
        href={`/projects/${projectId}/deliverables`}
        className="hover:underline"
      >
        Livrables
      </Link>
      <span>/</span>
      <span>{typeLabel}</span>
    </div>
  );
}
